import { query } from '../db/pool.js';
import { uniqueSlug } from '../utils/slug.js';
import { isFollowing } from './followRepository.js';
import { setArticleTags, tagsForArticle } from './tagRepository.js';
export type ArticleRow = any;
async function enrich(row:any,currentUserId?:number){ const tags=await tagsForArticle(row.id); const fav=(await query('select count(*)::int as count from favorites where article_id=$1',[row.id])).rows[0].count; const favorited=currentUserId ? (await query('select 1 from favorites where user_id=$1 and article_id=$2',[currentUserId,row.id])).rows.length>0 : false; return { slug:row.slug, title:row.title, description:row.description, body:row.body, tagList:tags, createdAt:new Date(row.created_at).toISOString(), updatedAt:new Date(row.updated_at).toISOString(), favorited, favoritesCount:Number(fav), author:{ username:row.username, bio:row.bio, image:row.image, following: await isFollowing(currentUserId,row.user_id) } }; }
export async function findArticleRow(slug:string){ return (await query('select a.*,u.username,u.bio,u.image from articles a join users u on u.id=a.user_id where a.slug=$1',[slug])).rows[0]; }
export async function getArticle(slug:string,currentUserId?:number){ const row=await findArticleRow(slug); return row ? enrich(row,currentUserId) : undefined; }
export async function createArticle(userId:number,data:{title:string;description:string;body:string;tagList:string[]}){ let slug=uniqueSlug(data.title); const row=(await query('insert into articles (user_id,slug,title,description,body) values ($1,$2,$3,$4,$5) returning *',[userId,slug,data.title,data.description,data.body])).rows[0]; await setArticleTags(row.id,data.tagList); return getArticle(row.slug,userId); }
export async function updateArticle(slug:string,userId:number,data:{title?:string;description?:string;body?:string;tagList?:string[]}){ const existing=await findArticleRow(slug); if(!existing) return undefined; if(existing.user_id!==userId) return 'forbidden'; const newSlug=data.title && data.title!==existing.title ? uniqueSlug(data.title) : slug; const row=(await query('update articles set slug=$1,title=$2,description=$3,body=$4,updated_at=now() where id=$5 returning *',[newSlug,data.title??existing.title,data.description??existing.description,data.body??existing.body,existing.id])).rows[0]; if(data.tagList) await setArticleTags(existing.id,data.tagList); return getArticle(row.slug,userId); }
export async function deleteArticle(slug:string,userId:number){ const existing=await findArticleRow(slug); if(!existing) return 'missing'; if(existing.user_id!==userId) return 'forbidden'; await query('delete from articles where id=$1',[existing.id]); return 'deleted'; }
export async function listArticles(filters:any,currentUserId?:number){ let sql='select distinct a.*,u.username,u.bio,u.image from articles a join users u on u.id=a.user_id'; const joins:string[]=[]; const where:string[]=[]; const params:any[]=[]; if(filters.tag){ joins.push('join article_tags at on at.article_id=a.id join tags t on t.id=at.tag_id'); params.push(filters.tag); where.push(`lower(t.name)=lower($${params.length})`); } if(filters.author){ params.push(filters.author); where.push(`lower(u.username)=lower($${params.length})`); } if(filters.favorited){ joins.push('join favorites ff on ff.article_id=a.id join users fu on fu.id=ff.user_id'); params.push(filters.favorited); where.push(`lower(fu.username)=lower($${params.length})`); } if(filters.feedUserId){ joins.push('join follows fl on fl.followee_id=a.user_id'); params.push(filters.feedUserId); where.push(`fl.follower_id=$${params.length}`); } sql+=' '+joins.join(' '); if(where.length) sql+=' where '+where.join(' and '); sql+=' order by a.created_at desc, a.id desc'; const all=(await query(sql,params)).rows; const page=all.slice(filters.offset, filters.offset+filters.limit); return { articles: await Promise.all(page.map(r=>enrich(r,currentUserId))), articlesCount: all.length }; }
