import { Router } from 'express';
import { optionalAuth, requireAuth } from '../middleware/auth.js';
import { allTags } from '../repositories/tagRepository.js';
import { parsePagination } from '../utils/pagination.js';
import { arrayOfStrings, required } from '../utils/validators.js';
import * as service from '../services/articleService.js';
export const articleRoutes=Router();
const param=(value:unknown)=>String(Array.isArray(value)?value[0]:value);
articleRoutes.get('/articles', optionalAuth, async (req,res,next)=>{ try{ res.json(await service.list({ ...parsePagination(req.query), tag:req.query.tag, author:req.query.author, favorited:req.query.favorited }, req.user?.id)); }catch(e){ next(e); } });
articleRoutes.get('/articles/feed', requireAuth, async (req,res,next)=>{ try{ res.json(await service.list({ ...parsePagination(req.query), feedUserId:req.user!.id }, req.user!.id)); }catch(e){ next(e); } });
articleRoutes.post('/articles', requireAuth, async (req,res,next)=>{ try{ const a=req.body.article??{}; res.status(201).json({ article: await service.create(req.user!.id,{ title:required(a.title,'title'), description:required(a.description,'description'), body:required(a.body,'body'), tagList:arrayOfStrings(a.tagList) }) }); }catch(e){ next(e); } });
articleRoutes.get('/articles/:slug', optionalAuth, async (req,res,next)=>{ try{ res.json({ article: await service.getArticle(param(req.params.slug), req.user?.id) }); }catch(e){ next(e); } });
articleRoutes.put('/articles/:slug', requireAuth, async (req,res,next)=>{ try{ const a=req.body.article??{}; res.json({ article: await service.update(param(req.params.slug), req.user!.id,{ title:a.title, description:a.description, body:a.body, tagList:Array.isArray(a.tagList)?a.tagList:undefined }) }); }catch(e){ next(e); } });
articleRoutes.delete('/articles/:slug', requireAuth, async (req,res,next)=>{ try{ await service.remove(param(req.params.slug), req.user!.id); res.status(204).end(); }catch(e){ next(e); } });
articleRoutes.post('/articles/:slug/favorite', requireAuth, async (req,res,next)=>{ try{ res.json({ article: await service.favoriteArticle(param(req.params.slug), req.user!.id) }); }catch(e){ next(e); } });
articleRoutes.delete('/articles/:slug/favorite', requireAuth, async (req,res,next)=>{ try{ res.json({ article: await service.unfavoriteArticle(param(req.params.slug), req.user!.id) }); }catch(e){ next(e); } });
articleRoutes.get('/articles/:slug/comments', optionalAuth, async (req,res,next)=>{ try{ res.json({ comments: await service.comments(param(req.params.slug), req.user?.id) }); }catch(e){ next(e); } });
articleRoutes.post('/articles/:slug/comments', requireAuth, async (req,res,next)=>{ try{ res.status(201).json({ comment: await service.addComment(param(req.params.slug), req.user!.id, required(req.body.comment?.body,'body')) }); }catch(e){ next(e); } });
articleRoutes.delete('/articles/:slug/comments/:id', requireAuth, async (req,res,next)=>{ try{ await service.removeComment(param(req.params.slug), Number(param(req.params.id)), req.user!.id); res.status(204).end(); }catch(e){ next(e); } });
articleRoutes.get('/tags', async (_req,res,next)=>{ try{ res.json({ tags: await allTags() }); }catch(e){ next(e); } });
