import { Anchor, Button, Card, Container, Group, Paper, Stack, Text, Textarea, Title } from '@mantine/core';
import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api/client';
import type { Article, Comment } from '../api/types';
import { useAuth } from '../auth/AuthContext';
import { ArticleMeta } from '../components/ArticleMeta';
import { FavoriteButton } from '../components/FavoriteButton';
import { TagList } from '../components/TagList';
export function ArticlePage(){ const {slug=''}=useParams(); const nav=useNavigate(); const {user}=useAuth(); const [article,setArticle]=useState<Article>(); const [comments,setComments]=useState<Comment[]>([]); const [body,setBody]=useState(''); useEffect(()=>{ api.getArticle(slug).then(r=>setArticle(r.article)); api.comments(slug).then(r=>setComments(r.comments)); },[slug]); if(!article) return <Container size="lg"><Text>Loading...</Text></Container>; const owner=user?.username===article.author.username; async function del(){ await api.deleteArticle(article!.slug); nav('/'); } async function add(e:FormEvent){ e.preventDefault(); const r=await api.addComment(slug,body); setComments([...comments,r.comment]); setBody(''); } async function delComment(id:number){ await api.deleteComment(slug,id); setComments(comments.filter(c=>c.id!==id)); } return <Container size="md"><Stack gap="xl"><Paper component="article" withBorder shadow="sm" radius="md" p="xl"><Stack gap="md"><Title order={1}>{article.title}</Title><Group justify="space-between" align="center"><ArticleMeta article={article}/><FavoriteButton article={article} onChange={setArticle}/></Group>{owner&&<Group><Button component={Link} to={`/editor/${article.slug}`} variant="light" color="green">Edit Article</Button><Button color="red" variant="light" onClick={del}>Delete Article</Button></Group>}<Text className="article-body">{article.body}</Text><TagList tags={article.tagList}/></Stack></Paper><Stack component="section" gap="md"><Title order={2}>Comments</Title>{user?<form onSubmit={add}><Stack><Textarea label="Comment" aria-label="Comment" minRows={4} value={body} onChange={e=>setBody(e.currentTarget.value)}/><Button type="submit" color="green">Post Comment</Button></Stack></form>:<Text><Anchor component={Link} to="/login">Sign in</Anchor> or <Anchor component={Link} to="/register">sign up</Anchor> to add comments.</Text>}{comments.map(c=><Card key={c.id} withBorder radius="md"><Stack gap="xs"><Text className="comment-body">{c.body}</Text><Group justify="space-between"><Text size="sm" c="dimmed">{c.author.username}</Text>{user?.username===c.author.username&&<Button size="xs" color="red" variant="subtle" onClick={()=>delComment(c.id)}>Delete Comment</Button>}</Group></Stack></Card>)}</Stack></Stack></Container>; }
