import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../api/client';
import type { Article, Comment } from '../api/types';
import { useAuth } from '../auth/AuthContext';
import { ArticleMeta } from '../components/ArticleMeta';
import { FavoriteButton } from '../components/FavoriteButton';
import { TagList } from '../components/TagList';
export function ArticlePage(){ const {slug=''}=useParams(); const nav=useNavigate(); const {user}=useAuth(); const [article,setArticle]=useState<Article>(); const [comments,setComments]=useState<Comment[]>([]); const [body,setBody]=useState(''); useEffect(()=>{ api.getArticle(slug).then(r=>setArticle(r.article)); api.comments(slug).then(r=>setComments(r.comments)); },[slug]); if(!article) return <p>Loading...</p>; const owner=user?.username===article.author.username; async function del(){ await api.deleteArticle(article!.slug); nav('/'); } async function add(e:FormEvent){ e.preventDefault(); const r=await api.addComment(slug,body); setComments([...comments,r.comment]); setBody(''); } async function delComment(id:number){ await api.deleteComment(slug,id); setComments(comments.filter(c=>c.id!==id)); } return <main><article><h1>{article.title}</h1><ArticleMeta article={article}/><FavoriteButton article={article} onChange={setArticle}/>{owner&&<span><Link to={`/editor/${article.slug}`}>Edit Article</Link><button onClick={del}>Delete Article</button></span>}<p>{article.body}</p><TagList tags={article.tagList}/></article><section><h2>Comments</h2>{user?<form onSubmit={add}><textarea aria-label="Comment" value={body} onChange={e=>setBody(e.target.value)}/><button>Post Comment</button></form>:<p><Link to="/login">Sign in</Link> or <Link to="/register">sign up</Link> to add comments.</p>}{comments.map(c=><div key={c.id} className="comment"><p>{c.body}</p><small>{c.author.username}</small>{user?.username===c.author.username&&<button onClick={()=>delComment(c.id)}>Delete Comment</button>}</div>)}</section></main>; }
