import { Badge, Card, Container, Grid, Stack, Tabs, Text, Title } from '@mantine/core';
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../api/client';
import type { Article } from '../api/types';
import { useAuth } from '../auth/AuthContext';
import { ArticlePreview } from '../components/ArticlePreview';
import { Pagination } from '../components/Pagination';
import { TagList } from '../components/TagList';
const limit=10;
export function HomePage(){ const {user}=useAuth(); const [sp]=useSearchParams(); const nav=useNavigate(); const [tab,setTab]=useState<'global'|'feed'>('global'); const [articles,setArticles]=useState<Article[]>([]); const [count,setCount]=useState(0); const [tags,setTags]=useState<string[]>([]); const page=Number(sp.get('page')??0); const tag=sp.get('tag'); useEffect(()=>{ api.tags().then(r=>setTags(r.tags)); },[]); useEffect(()=>{ const q=`?limit=${limit}&offset=${page*limit}${tag?`&tag=${tag}`:''}`; (tab==='feed'?api.feed(q):api.listArticles(q)).then(r=>{setArticles(r.articles);setCount(r.articlesCount);}); },[tab,page,tag]); return <Container size="lg"><Stack gap="xl"><Stack gap={0} ta="center" py="xl"><Title order={1} c="green">conduit</Title><Text c="dimmed">A place to share your knowledge.</Text></Stack><Grid gap="lg"><Grid.Col span={{base:12,md:8}}><Stack gap="md"><Tabs value={tab} onChange={v=>setTab((v as 'global'|'feed') ?? 'global')} color="green"><Tabs.List><Tabs.Tab value="global">Global Feed</Tabs.Tab>{user&&<Tabs.Tab value="feed">Your Feed</Tabs.Tab>}{tag&&<Tabs.Tab value="tag" disabled>#{tag}</Tabs.Tab>}</Tabs.List></Tabs>{articles.length?articles.map(a=><ArticlePreview key={a.slug} article={a}/>):<Text c="dimmed">No articles are here... yet.</Text>}<Pagination count={count} limit={limit} page={page} onPage={p=>nav(`/?page=${p}${tag?`&tag=${tag}`:''}`)}/></Stack></Grid.Col><Grid.Col span={{base:12,md:4}}><Card withBorder radius="md" shadow="sm"><Stack gap="md"><Title order={2} size="h4">Popular Tags</Title>{tag&&<Badge color="green" variant="light">Filtering #{tag}</Badge>}<TagList tags={tags} onSelect={t=>nav(`/?tag=${t}`)}/></Stack></Card></Grid.Col></Grid></Stack></Container>; }
